;;; init-keybinding.el --- Keybinding -*- lexical-binding: t -*-

(use-package meow
  :ensure t
  :config
  (meow-global-mode 1)
  (setq meow-use-clipboard t)

  (meow-thing-register 'angle
                       '(pair ("<") (">"))
                       '(pair ("<") (">")))

  (setq meow-char-thing-table
        '((?b . round)
          (?f . square)
          (?h . curly)
          (?a . angle)
          (?d . defun)
          (?s . string)
          (?p . paragraph)
          (?l . line)
          (?x . buffer)))

  (meow-leader-define-key
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet))

  (meow-normal-define-key
   '("a" . meow-beginning-of-thing)
   '("b" . meow-back-word)
   '("c" . meow-change)
   '("d" . meow-kill)
   '("e" . meow-end-of-thing)
   '("g" . meow-block)
   '("h" . meow-left)
   '("i" . meow-insert)
   '("j" . meow-next)
   '("k" . meow-prev)
   '("l" . meow-right)
   '("m" . meow-line)
   '("o" . meow-open-below)
   '("p" . meow-yank)
   '("q" . meow-join)
   '("r" . meow-replace)
   '("s" . meow-next-symbol)
   '("t" . meow-append)
   '("u" . undo-only)
   '("w" . meow-next-word)
   '("x" . (lambda () (interactive) (meow-right-expand) (meow-kill)))
   '("y" . meow-clipboard-save)
   '("z" . meow-search)
   '("D" . meow-backward-delete)
   '("E" . meow-to-block)
   '("H" . meow-left-expand)
   '("I" . meow-append)
   '("J" . meow-next-expand)
   '("K" . meow-prev-expand)
   '("L" . meow-right-expand)
   '("O" . meow-open-above)
   '("P" . meow-yank-pop)
   '("R" . undo-redo)
   '("S" . meow-mark-symbol)
   '("W" . meow-mark-word)
   '("X" . meow-delete)
   '("0" . meow-expand-0)
   '("1" . meow-expand-1)
   '("2" . meow-expand-2)
   '("3" . meow-expand-3)
   '("4" . meow-expand-4)
   '("5" . meow-expand-5)
   '("6" . meow-expand-6)
   '("7" . meow-expand-7)
   '("8" . meow-expand-8)
   '("9" . meow-expand-9)
   '("." . meow-bounds-of-thing)
   '("," . meow-inner-of-thing)
   '("'" . meow-reverse)

   ;; prefix v
   '("va" . meow-find)
   '("vb" . (lambda () (interactive) (meow-till 1 40)))
   '("vc" . meow-save-char)
   '("ve" . meow-end-kmacro)
   '("vf" . (lambda () (interactive) (meow-till 1 91)))
   '("vg" . meow-grab)
   '("vh" . meow-left-expand)
   '("vj" . meow-next-expand )
   '("vk" . meow-start-kmacro-or-insert-counter)
   '("vk" . meow-prev-expand)
   '("vl" . meow-right-expand)
   '("vp" . p-mark-paragraph)
   '("vr" . meow-query-replace-regexp)
   '("vs" . meow-mark-symbol)
   '("vv" . meow-visit)
   '("vw" . meow-mark-word)
   '("vx" . meow-swap-grab)

   ;; prefix n
   '("nd" . (lambda () (interactive) (prot-pair-insert '(?\" . ?\") 1)))
   '("nf" . (lambda () (interactive) (prot-pair-insert '(?\[ . ?\]) 1)))
   '("nh" . (lambda () (interactive) (prot-pair-insert '(?\{ . ?\}) 1)))
   '("nk" . (lambda () (interactive) (prot-pair-insert '(?\( . ?\)) 1)))
   '("nn" . prot-pair-delete)
   '("ns" . (lambda () (interactive) (prot-pair-insert '(?\' . ?\') 1)))

   ;; prefix f
   '("fa" . lsp-bridge-find-def)
   '("fb" . lsp-bridge-find-def-return)
   '("fc" . prot-comment)
   '("fe" . eval-buffer)
   '("ff" . find-file)
   '("fg" . prot-search-grep)
   '("fh" . indent-rigidly-left-to-tab-stop)
   '("fi" . indent-region)
   '("fl" . indent-rigidly-right-to-tab-stop)
   '("fn" . consult-line)
   '("fp" . consult-ripgrep)
   '("fr" . recentf)
   '("fs" . save-buffer)
   '("fv" . p-open-html-in-browser)
   '("fw" . mark-whole-buffer)
   '("fx" . execute-extended-command)

   '("<escape>" . ignore))

  (define-key meow-insert-state-keymap (kbd "C-g") 'meow-insert-exit)
  (define-key meow-keypad-state-keymap (kbd "C-g") 'meow-keypad-quit)
  (define-key meow-insert-state-keymap (kbd "C-k") 'delete-backward-char)
  (define-key meow-insert-state-keymap (kbd "C-w") 'backward-kill-word))

(use-package prot-prefix
  :ensure nil
  :bind-keymap
  ((";" . prot-prefix)))

(provide 'init-keybinding)
